name: Go package

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: nextcloud:latest
        ports:
          - 18080:80
        env:
          SQLITE_DATABASE: nextcloud
          NEXTCLOUD_ADMIN_USER: admin
          NEXTCLOUD_ADMIN_PASSWORD: password

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Test
        run: go test -v ./...

      - name: Run vet & lint
        run: |
          go vet .
          golint .

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build .